name: places_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget.
version: 2.1.6
homepage: https://github.com/ahmednafea/places_picker
issue_tracker: https://github.com/ahmednafea/places_picker/issues
repository: https://github.com/ahmednafea/places_picker

platforms:
  android:
  ios:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  google_maps_webservice:
    git: https://github.com/ShehanYjoz/google_maps_webservice.git
  google_api_headers: ^4.6.1
  tuple: ^2.0.2
  http: ^1.5.0
dependency_overrides:
  http:  ">=0.13.0"
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

screenshots:
  - screenshot2.png
